### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by akshayrathodar** [saimj7/Social-Distancing-Detection-in-Real-Time#3]
Hello  My Friend , sorry for Disturbing you but my question is i use i3 with Ubuntu but every frame lagging by 3 sec interval so its not looks pretty any system requirement to handle this script ?? And Also having a question like how can i use this in CCTV grid like 4 cameras together.

**Comment by saimj7** [comment]
Hi, you need a good enough gpu to be able to run this without lag. Try running with threading as it is intended for skipping delayed frames in order to catch up with new frames, thus reducing the lag. Regarding cctv: you can again use threading to run threads for different camera streams but that would require a decent cpu and gpu.
