### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SamiurRahman1** [saimj7/Social-Distancing-Detection-in-Real-Time#4]
Hello, i am having a little problem understanding how we know that the distance between two detected persons is 1.5 or 2 meters? How do we determine/proximate the distance in meters from the euclidean distance between two objects?

Thanks

**Comment by saimj7** [comment]
Hi, the distance is only computed via pair-wise pixel differences. In order to accurately map the pixels into meters or feet, we need better camera calibration. You could try using stereovision or implement a perspective transform, however, complexity would be increased. Example: https://www.reddit.com/r/computervision/comments/gf4zhj/automatic_social_distance_measurement/

**Comment by SamiurRahman1** [comment]
Understood. Thank you so much for your reply.
